version: '3.8'
services:
  postgres:
    env_file:
      - ./.env
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      - POSTGRES_DB=crud
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '4400:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=${POSTGRES_USER} --dbname=crud"
        ]
      interval: 20s
      timeout: 5s
      retries: 3
volumes:
  postgres: null
networks:
  outpost_network:
    external: true